config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  get "expenses" => "expenses#index"
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :time, presence: true

  after_create :reminder

  @@REMINDER_TIME = 30.minutes # minutes before appointment

  # Notify our appointment attendee X minutes before the appointment time
  def reminder

    account_sid = 'AC3d3d6027333ad86503dfe14bc2c3bbca'
    auth_token = '3af8403ac5d76142f655b1628b8b9249'

   # set up a client to talk to the Twilio REST API 
   @client = Twilio::REST::Client.new account_sid, auth_token
   puts @client.inspect
   sms = @client.account.sms.messages.create(:body => "All in the game, yo",
    :to => self.phone_number,
    :from => "+15005550006")

    puts message.to
  end

  def when_to_run
    time - @@REMINDER_TIME
  end

  handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }
end

app/models/expense.rb
require 'twilio-ruby'
class Expense < ActiveRecord::Base

  def self.min_amount_sum
     min_arr,max_arr, min_sum, max_sum = [],[], 0, 0
     expenses = Expense.all
     expenses.each do |e|
       min_arr << e.min_amount
       min_sum = min_arr.sum
      
       max_arr << e.max_amount if e.max_amount
       max_sum = max_arr.sum
      
     end
   return min_sum, max_sum
  end


  def send_text_message
    account_sid = 'AC3d3d6027333ad86503dfe14bc2c3bbca'
    auth_token = '3af8403ac5d76142f655b1628b8b9249' 
 
   # set up a client to talk to the Twilio REST API 
   @client = Twilio::REST::Client.new account_sid, auth_token 
   puts @client.inspect
   sms = @client.account.sms.messages.create(:body => "All in the game, yo",
    :to => "+14807382660",
    :from => "+15005550006") 
   #puts sms.body

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
    if @appointments.length == 0
      flash[:alert] = "You have no appointments. Create one now to get started."
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    Time.zone = appointment_params[:time_zone]
    @appointment = Appointment.new(appointment_params)
    
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :phone_number, :time)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

	def index
	  @expenses =  Expense.all
          
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment, :html => { :class => "form-horizontal appointment" } do |f| %>

  <% if @appointment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%#=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%#=f.error_span(:phone_number) %>
  </div>
  <div class="form-group">
    <%= f.label :time, "Time and Date", :class => 'control-label col-lg-2' %>
    <!-- Rails expects time_select when dealing with ActiveRecord forms -->
    <div class="col-lg-2">
      <%= time_select :appointment, :time, {:class => "form-control" } %>
    </div>
    <div class="col-lg-4">
      <%= date_select :appointment, :time, {:class => "form-control" } %>
    </div>
    <div class="col-lg-2">
      <%= f.time_zone_select :time, ActiveSupport::TimeZone.all.sort, default: "Pacific Time (US & Canada)" %>
    </div>
    <%#=f.error_span(:time) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                appointments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to appointment.id, appointment_path(appointment) %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.phone_number %></td>
        <td><%= appointment.time %></td>
        <td><%=l appointment.created_at %></td>
        <td>
          <%= link_to "Edit", 
                      edit_appointment_path(appointment), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Delete",
                      appointment_path(appointment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New",
            new_appointment_path,
            :class => 'btn btn-primary' %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @appointment.phone_number %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/expenses/index.html.erb
<h1><%= pluralize(@expenses.count, "Item")%> </h1>
<table border=1>
<tr border=1>

    <td>Sr. No:</td>
    <td>Item</td>
    <td>Min Amount</td>
    <td>Max Amount</td>
</tr>

<% @expenses.each do |e| %>
  <br>
    <tr border=1>

    <td><%= e.id %></td>
    <td><%= e.item %></td>
    <td><%= e.min_amount %></td>
    <td><%= e.max_amount %></td>
  <%end%>
</tr>

<tr border=0>
  <td></td>
  <td><strong>Sum</strong></td>
  <td><strong><%= number_to_currency(Expense.min_amount_sum[0]) %></strong></td>
  <td><strong><%= number_to_currency(Expense.min_amount_sum[1]) %></strong></td>
</tr>
    


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonthlyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>